### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by hadess** [flathub/org.gnome.Polari#22]
Polari crashes a number of seconds after starting up.
```
#0  0x00007f93306d77cb in slab_allocator_free_chunk (chunk_size=chunk_size@entry=80, mem=mem@entry=0x5560499e1380) at ../glib/gslice.c:1415
#1  0x00007f93306d7ace in magazine_cache_trim (local_allocator=0x7f933079ddc0 <allocator>, stamp=<optimized out>, ix=<optimized out>) at ../glib/gslice.c:725
#2  magazine_cache_push_magazine (ix=<optimized out>, magazine_chunks=<optimized out>, count=20) at ../glib/gslice.c:756
#3  0x00007f93306d8c86 in thread_memory_magazine2_unload (tmem=0x556045f0f7d0, ix=<optimized out>) at ../glib/gslice.c:855
#4  g_slice_free1 (mem_size=<optimized out>, mem_block=0x55604a6eea60) at ../glib/gslice.c:1167
#5  0x00007f93304fd42c in BoxedInstance::~BoxedInstance() (this=0x5560462cd950, __in_chrg=<optimized out>) at ../gi/wrapperutils.h:996
#6  0x00007f9330500d7c in GIWrapperInstance<BoxedBase, BoxedPrototype, BoxedInstance, void>::finalize_impl(JS::GCContext*, JSObject*) (this=0x5560462cd950) at ../gi/wrapperutils.h:1112
#7  GIWrapperBase<BoxedBase, BoxedPrototype, BoxedInstance>::finalize(JS::GCContext*, JSObject*) (gcx=<optimized out>, obj=0xa0096324308) at ../gi/wrapperutils.h:410
#8  0x00007f932f83f7e4 in JSClass::doFinalize(JS::GCContext*, JSObject*) const (obj=0xa0096324308, gcx=0x556045f39718, this=<optimized out>) at /usr/lib/debug/source/sdk/mozjs.bst/build-dir/dist/include/js/Class.h:649
#9  JSObject::finalize(JS::GCContext*) (gcx=0x556045f39718, this=0xa0096324308) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/vm/JSObject-inl.h:97
#10 js::gc::Arena::finalize<JSObject>(JS::GCContext*, js::gc::AllocKind, unsigned long) (thingSize=40, thingKind=<optimized out>, gcx=<optimized out>, this=0xa0096324000) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/gc/Sweeping.cpp:128
#11 FinalizeTypedArenas<JSObject>(JS::GCContext*, js::gc::ArenaList&, js::gc::SortedArenaList&, js::gc::AllocKind, js::SliceBudget&) (gcx=<optimized out>, src=<optimized out>, dest=<optimized out>, thingKind=<optimized out>, budget=<optimized out>) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/gc/Sweeping.cpp:194
#12 0x00007f932f84a47f in js::gc::GCRuntime::foregroundFinalize(JS::GCContext*, JS::Zone*, js::gc::AllocKind, js::SliceBudget&, js::gc::SortedArenaList&) (sweepList=..., sliceBudget=..., thingKind=js::gc::AllocKind::OBJECT2, zone=0x556045fd5720, gcx=0x556045f39718, this=0x556045f39700) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/gc/Sweeping.cpp:1693
#13 js::gc::GCRuntime::finalizeAllocKind(JS::GCContext*, js::SliceBudget&) (this=0x556045f39700, gcx=0x556045f39718, budget=...) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/gc/Sweeping.cpp:1894
#14 0x00007f932f83dae5 in sweepaction::SweepActionForEach<ContainerIter<mozilla::EnumSet<js::gc::AllocKind, unsigned long> >, mozilla::EnumSet<js::gc::AllocKind, unsigned long> >::run(js::gc::SweepAction::Args&) (this=0x556045f4b1f0, args=...) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/gc/Sweeping.cpp:2120
#15 0x00007f932f83d77c in sweepaction::SweepActionSequence::run(js::gc::SweepAction::Args&) (this=0x556045f4b260, args=...) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/gc/Sweeping.cpp:2085
#16 0x00007f932f83d68e in sweepaction::SweepActionForEach<js::gc::SweepGroupZonesIter, JSRuntime*>::run(js::gc::SweepAction::Args&) (this=0x556045f4b310, args=...) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/gc/Sweeping.cpp:2120
#17 0x00007f932f83d77c in sweepaction::SweepActionSequence::run(js::gc::SweepAction::Args&) (this=0x556045f4b410, args=...) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/gc/Sweeping.cpp:2085
#18 0x00007f932f84aad5 in sweepaction::SweepActionForEach<js::gc::SweepGroupsIter, JSRuntime*>::run(js::gc::SweepAction::Args&) (this=0x556045f4b510, args=...) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/gc/Sweeping.cpp:2120
#19 0x00007f932f84cb07 in js::gc::GCRuntime::performSweepActions(js::SliceBudget&) (this=this@entry=0x556045f39700, budget=...) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/gc/Sweeping.cpp:2256
#20 0x00007f932f823b45 in js::gc::GCRuntime::incrementalSlice(js::SliceBudget&, JS::GCReason, bool) (this=this@entry=0x556045f39700, budget=..., reason=JS::GCReason::MEM_PRESSURE, budgetWasIncreased=budgetWasIncreased@entry=false) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/gc/GC.cpp:3251
#21 0x00007f932f824129 in js::gc::GCRuntime::gcCycle(bool, js::SliceBudget const&, JS::GCReason) (this=0x556045f39700, nonincrementalByAPI=<optimized out>, budgetArg=<optimized out>, reason=<optimized out>) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/gc/GC.cpp:3732
#22 0x00007f932f8243bf in js::gc::GCRuntime::collect(bool, js::SliceBudget const&, JS::GCReason) (this=0x556045f39700, nonincrementalByAPI=<optimized out>, budget=..., reason=JS::GCReason::MEM_PRESSURE) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/gc/GC.cpp:3916
#23 0x00007f932f824786 in js::gc::GCRuntime::gc(JS::GCOptions, JS::GCReason) (this=<optimized out>, options=options@entry=JS::GCOptions::Normal, reason=reason@entry=JS::GCReason::MEM_PRESSURE) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/gc/GC.cpp:3994
#24 0x00007f932f643291 in JS_GC(JSContext*, JS::GCReason) (cx=<optimized out>, reason=reason@entry=JS::GCReason::MEM_PRESSURE) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/jsapi.cpp:1305
#25 0x00007f93305425be in GjsContextPrivate::trigger_gc_if_needed(void*) (data=0x556045f38020, data@entry=<error reading variable: value has been optimized out>) at ../gjs/context.cpp:838
#26 0x00007f93306b937f in g_timeout_dispatch (source=0x556049a1b210, callback=<optimized out>, user_data=<optimized out>) at ../glib/gmain.c:5017
#27 0x00007f93306b8681 in g_main_dispatch (context=<optimized out>) at ../glib/gmain.c:3454
#28 g_main_context_dispatch (context=<optimized out>) at ../glib/gmain.c:4172
#29 0x00007f93306b8bd8 in g_main_context_iterate (context=context@entry=0x556045f81780, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4248
#30 0x00007f93306b8c73 in g_main_context_iteration (context=context@entry=0x556045f81780, may_block=may_block@entry=1) at ../glib/gmain.c:4313
#31 0x00007f93308fcd1d in g_application_run (application=0x55604647b100 [Gjs_Application], argc=<optimized out>, argv=<optimized out>) at ../gio/gapplication.c:2573
#32 0x00007f9330465056 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#33 0x00007f9330463add in ffi_call_int (cif=<optimized out>, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=<optimized out>) at ../src/x86/ffi64.c:673
#34 0x00007f93304642b3 in ffi_call (cif=0x5560460f1c50, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>) at ../src/x86/ffi64.c:710
#35 0x00007f933050af34 in Gjs::Function::invoke(JSContext*, JS::CallArgs const&, JS::Handle<JSObject*>, _GIArgument*) (this=0x5560460f1c30, context=0x556045f37220, args=<optimized out>, this_obj=..., r_value=<optimized out>) at ../gi/function.cpp:1041
#36 0x00007f933050b728 in Gjs::Function::call(JSContext*, unsigned int, JS::Value*) (context=0x556045f37220, js_argc=<optimized out>, vp=<optimized out>) at ../gi/function.cpp:1221
#37 0x00007f932f366990 in CallJSNative(JSContext*, bool (*)(JSContext*, unsigned int, JS::Value*), js::CallReason, JS::CallArgs const&) (args=..., reason=js::CallReason::Call, native=0x7f933050b640 <Gjs::Function::call(JSContext*, unsigned int, JS::Value*)>, cx=0x556045f37220) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/vm/Interpreter.cpp:420
#38 js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct, js::CallReason) (cx=0x556045f37220, args=..., construct=<optimized out>, reason=js::CallReason::Call) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/vm/Interpreter.cpp:493
#39 0x00007f932f35a487 in InternalCall (reason=<optimized out>, args=<optimized out>, cx=<optimized out>) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/vm/Interpreter.cpp:574
#40 js::CallFromStack(JSContext*, JS::CallArgs const&) (args=<optimized out>, cx=<optimized out>) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/vm/Interpreter.cpp:578
#41 Interpret(JSContext*, js::RunState&) (cx=0x556045f37220, state=...) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/vm/Interpreter.cpp:3314
#42 0x00007f932f36615b in js::RunScript(JSContext*, js::RunState&) (cx=0x556045f37220, state=...) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/vm/Interpreter.cpp:389
#43 0x00007f932f3684fa in js::ExecuteKernel(JSContext*, JS::Handle<JSScript*>, JS::Handle<JSObject*>, js::AbstractFramePtr, JS::MutableHandle<JS::Value>) (result=..., evalInFrame=..., envChainArg=..., script=..., cx=0x556045f37220) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/vm/Interpreter.cpp:781
#44 js::Execute(JSContext*, JS::Handle<JSScript*>, JS::Handle<JSObject*>, JS::MutableHandle<JS::Value>) (cx=0x556045f37220, script=script@entry=..., envChain=envChain@entry=..., rval=...) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/vm/Interpreter.cpp:813
#45 0x00007f932f3c30f7 in js::ModuleObject::execute(JSContext*, JS::Handle<js::ModuleObject*>, JS::MutableHandle<JS::Value>) (cx=<optimized out>, self=self@entry=..., rval=...) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/builtin/ModuleObject.cpp:1249
#46 0x00007f932f537b48 in intrinsic_ExecuteModule(JSContext*, unsigned int, JS::Value*) (cx=<optimized out>, argc=<optimized out>, vp=<optimized out>) at /usr/lib/debug/source/sdk/mozjs.bst/js/src/vm/SelfHosting.cpp:1891
```

Might be an issue with the runtime:
```
$ flatpak info org.gnome.Polari

Polari - Talk to people on IRC

          ID: org.gnome.Polari
         Ref: app/org.gnome.Polari/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 43.0
     License: GPL-2.0+ and LGPL-2.1+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 4.9 MB
     Runtime: org.gnome.Platform/x86_64/43
         Sdk: org.gnome.Sdk/x86_64/43

      Commit: eab7777cacb3644693cac4f7be2ee5c4edf47561cec4225b51cea6ac1856bb26
      Parent: d4c48ffa82ba06ae838905942039a98a39ec29e886c128ffab942c0d63f6214f
     Subject: Update to 43.0 (cf8a374c)
        Date: 2022-09-29 19:18:24 +0000
```

**Comment by fmuellner** [comment]
> Might be an issue with the runtime

I suspect it is.

Can you still reproduce the crash if you run with
```sh
$ flatpak run --runtime-version=44 org.gnome.Polari//stable
```

**Comment by hadess** [comment]
It doesn't crash after a couple of seconds! And I learnt that you can override the runtime version!
